#ifndef VBOOKRSC_H
#define VBOOKRSC_H

//	Header generated by Constructor for Palm OS (R) 1.9.1
//
//	Generated at 14:57:11  on 2007Äê6ÔÂ17ÈÕ
//
//	Generated for file: VBook.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE
//	DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name:   		"VBook"
//
//	Palm App Version:		"2.31"


//	Resource: tFRM 1000
#define MainForm                                  1000	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 1000, Default Button ID = 0)
#define MainUpButton                              1006	//(Left Origin = 54, Top Origin = 2, Width = 12, Height = 10, Usable = 0, Anchor Left = 1, Frame = 0, Non-bold Frame = 1, Font = Standard)
#define MainSwitchButton                          1021	//(Left Origin = 40, Top Origin = 1, Width = 12, Height = 11, Usable = 1, Anchor Left = 1, Frame = 0, Non-bold Frame = 0, Font = Standard)
#define MainUpBitMap                              1011	//(Left Origin = 54, Top Origin = 2, Bitmap Resource ID = 1011, Usable = 0)
#define MainHandheldBitMap                        1014	//(Left Origin = 40, Top Origin = 1, Bitmap Resource ID = 1014, Usable = 0)
#define MainCardBitMap                            1015	//(Left Origin = 40, Top Origin = 1, Bitmap Resource ID = 1015, Usable = 0)
#define MainDirField                              1010	//(Left Origin = 70, Top Origin = 1, Width = 90, Height = 12, Usable = 0, Editable = 0, Underline = 0, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 40, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainBooksGadget                           1005	//(Left Origin = 0, Top Origin = 17, Width = 152, Height = 130, Usable = 1)
#define MainOperationList                         1003	//(Left Origin = 1, Top Origin = 92, Width = 54, Usable = 0, Font = Standard, Visible Items = 6)
#define MainClassList                             1007	//(Left Origin = 79, Top Origin = 1, Width = 80, Usable = 0, Font = Standard, Visible Items = 3)
#define MainVolsList                              1020	//(Left Origin = 40, Top Origin = 14, Width = 80, Usable = 0, Font = Standard, Visible Items = 2)
#define MainCategoryPopTrigger                    1001	//(Left Origin = 113, Top Origin = 1, Width = 47, Height = 12, Usable = 0, Anchor Left = 0, Font = Standard, List ID = 1007)
#define MainChoicesPopTrigger                     1002	//(Left Origin = 0, Top Origin = 148, Width = 50, Height = 12, Usable = 1, Anchor Left = 1, Font = Standard, List ID = 1003)
#define MainVsbarScrollBar                        1004	//(Left Origin = 153, Top Origin = 17, Width = 7, Height = 130, Usable = 1, Value = 0, Minimum Value = 0, Maximum Value = 0, Page Size = 0)

//	Resource: tFRM 1100
#define AboutForm                                 1100	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 156, Usable = 1, Modal = 1, Save Behind = 0, Help ID = 1000, Menu Bar ID = 0, Default Button ID = 0)
#define AboutOKButton                             1105	//(Left Origin = 5, Top Origin = 138, Width = 40, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define AboutUnnamed1108BitMap                    1100	//(Left Origin = 8, Top Origin = 24, Bitmap Resource ID = 1100, Usable = 1)
#define AboutAuthorLabel                          1101	//(Left Origin = 38, Top Origin = 69, Usable = 1, Font = Standard)
#define AboutTitleLabel                           1102	//(Left Origin = 38, Top Origin = 16, Usable = 1, Font = Bold)
#define AboutYearLabel                            1103	//(Left Origin = 38, Top Origin = 56, Usable = 1, Font = Standard)
#define AboutVerLabel                             1104	//(Left Origin = 38, Top Origin = 29, Usable = 1, Font = Bold)
#define AboutEmailLabel                           1106	//(Left Origin = 9, Top Origin = 84, Usable = 1, Font = Standard)
#define AboutCopyrightLabel                       1107	//(Left Origin = 38, Top Origin = 42, Usable = 1, Font = Bold)
#define AboutUnnamed1109Label                     1109	//(Left Origin = 9, Top Origin = 109, Usable = 1, Font = Standard)
#define AboutExpLabel                             1110	//(Left Origin = 68, Top Origin = 138, Usable = 0, Font = Bold)
#define AboutBuildLabel                           1111	//(Left Origin = 84, Top Origin = 29, Usable = 1, Font = Bold)

//	Resource: tFRM 1200
#define CategoriesForm                            1200	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 156, Usable = 1, Modal = 1, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define CategoriesOkButton                        1202	//(Left Origin = 5, Top Origin = 138, Width = 22, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define CategoriesNewButton                       1203	//(Left Origin = 34, Top Origin = 138, Width = 26, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define CategoriesRenameButton                    1204	//(Left Origin = 66, Top Origin = 138, Width = 40, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define CategoriesDeleteButton                    1205	//(Left Origin = 111, Top Origin = 138, Width = 40, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define CategoriesNameList                        1201	//(Left Origin = 8, Top Origin = 24, Width = 140, Usable = 1, Font = Standard, Visible Items = 9)

//	Resource: tFRM 1300
#define NewCateForm                               1300	//(Left Origin = 2, Top Origin = 84, Width = 156, Height = 74, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define NewCateOkButton                           1303	//(Left Origin = 6, Top Origin = 56, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define NewCateCancelButton                       1304	//(Left Origin = 49, Top Origin = 56, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define NewCateNameField                          1302	//(Left Origin = 5, Top Origin = 34, Width = 146, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 10, Font = Standard, Auto Shift = 1, Has Scroll Bar = 0, Numeric = 0)
#define NewCateCapGraffitiShift                   1305	//(Left Origin = 139, Top Origin = 59)
#define NewCateHintLabel                          1301	//(Left Origin = 7, Top Origin = 19, Usable = 1, Font = Bold)

//	Resource: tFRM 1400
#define InformationForm                           1400	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 156, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define InformationOkButton                       1401	//(Left Origin = 5, Top Origin = 138, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define InformationUnnamed1402Label               1402	//(Left Origin = 12, Top Origin = 32, Usable = 1, Font = Bold)
#define InformationUnnamed1403Label               1403	//(Left Origin = 13, Top Origin = 48, Usable = 1, Font = Bold)
#define InformationUnnamed1404Label               1404	//(Left Origin = 62, Top Origin = 17, Usable = 1, Font = Bold)
#define InformationUnnamed1405Label               1405	//(Left Origin = 103, Top Origin = 17, Usable = 1, Font = Bold)
#define InformationDynaFreeLabel                  1406	//(Left Origin = 62, Top Origin = 32, Usable = 1, Font = Standard)
#define InformationDynaTotalLabel                 1407	//(Left Origin = 103, Top Origin = 32, Usable = 1, Font = Standard)
#define InformationStorFreeLabel                  1408	//(Left Origin = 62, Top Origin = 48, Usable = 1, Font = Standard)
#define InformationStorTotalLabel                 1409	//(Left Origin = 103, Top Origin = 48, Usable = 1, Font = Standard)
#define InformationUnnamed1410Label               1410	//(Left Origin = 5, Top Origin = 70, Usable = 1, Font = Bold)
#define InformationFontLoadLabel                  1411	//(Left Origin = 62, Top Origin = 70, Usable = 1, Font = Standard)

//	Resource: tFRM 1500
#define ContentsForm                              1500	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 1200, Default Button ID = 0)
#define ContentsReturnButton                      1502	//(Left Origin = 148, Top Origin = 1, Width = 12, Height = 10, Usable = 1, Anchor Left = 1, Frame = 0, Non-bold Frame = 1, Font = Standard)
#define ContentsReturnBitMap                      1012	//(Left Origin = 148, Top Origin = 1, Bitmap Resource ID = 1012, Usable = 1)
#define ContentsTitlesGadget                      1503	//(Left Origin = 0, Top Origin = 17, Width = 152, Height = 143, Usable = 1)
#define ContentsVsbarScrollBar                    1504	//(Left Origin = 153, Top Origin = 17, Width = 7, Height = 143, Usable = 1, Value = 0, Minimum Value = 0, Maximum Value = 0, Page Size = 0)

//	Resource: tFRM 1600
#define ViewForm                                  1600	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 1100, Default Button ID = 0)
#define ViewCloseButton                           1603	//(Left Origin = 0, Top Origin = 152, Width = 8, Height = 8, Usable = 0, Anchor Left = 1, Frame = 0, Non-bold Frame = 1, Font = Standard)
#define ViewTOCButton                             1604	//(Left Origin = 9, Top Origin = 152, Width = 8, Height = 8, Usable = 0, Anchor Left = 1, Frame = 0, Non-bold Frame = 1, Font = Standard)
#define ViewBMButton                              1605	//(Left Origin = 18, Top Origin = 152, Width = 5, Height = 8, Usable = 0, Anchor Left = 1, Frame = 0, Non-bold Frame = 1, Font = Standard)
#define ViewBackButton                            1606	//(Left Origin = 25, Top Origin = 152, Width = 8, Height = 8, Usable = 0, Anchor Left = 1, Frame = 0, Non-bold Frame = 1, Font = Standard)
#define ViewHomeButton                            1607	//(Left Origin = 34, Top Origin = 152, Width = 8, Height = 8, Usable = 0, Anchor Left = 1, Frame = 0, Non-bold Frame = 1, Font = Standard)
#define ViewForwardButton                         1608	//(Left Origin = 43, Top Origin = 152, Width = 8, Height = 8, Usable = 0, Anchor Left = 1, Frame = 0, Non-bold Frame = 1, Font = Standard)
#define ViewPlayButton                            1609	//(Left Origin = 125, Top Origin = 152, Width = 8, Height = 8, Usable = 0, Anchor Left = 1, Frame = 0, Non-bold Frame = 1, Font = Standard)
#define ViewFindButton                            1610	//(Left Origin = 134, Top Origin = 152, Width = 8, Height = 8, Usable = 0, Anchor Left = 1, Frame = 0, Non-bold Frame = 1, Font = Standard)
#define ViewGotoButton                            1611	//(Left Origin = 143, Top Origin = 152, Width = 8, Height = 8, Usable = 0, Anchor Left = 1, Frame = 0, Non-bold Frame = 1, Font = Standard)
#define ViewCaptureButton                         1612	//(Left Origin = 152, Top Origin = 152, Width = 8, Height = 8, Usable = 0, Anchor Left = 1, Frame = 0, Non-bold Frame = 1, Font = Standard)
#define ViewPrgCancelButton                       1629	//(Left Origin = 61, Top Origin = 82, Width = 36, Height = 12, Usable = 0, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define ViewBatteryBitMap                         1013	//(Left Origin = 96, Top Origin = 0, Bitmap Resource ID = 1013, Usable = 0)
#define ViewStopBitMap                            1007	//(Left Origin = 125, Top Origin = 152, Bitmap Resource ID = 1007, Usable = 0)
#define ViewCopyBitMap                            1200	//(Left Origin = 152, Top Origin = 152, Bitmap Resource ID = 1200, Usable = 0)
#define ViewCopyPressedBitMap                     1300	//(Left Origin = 152, Top Origin = 152, Bitmap Resource ID = 1300, Usable = 0)
#define ViewCloseBitMap                           1000	//(Left Origin = 0, Top Origin = 152, Bitmap Resource ID = 1000, Usable = 0)
#define ViewContentsBitMap                        1001	//(Left Origin = 9, Top Origin = 152, Bitmap Resource ID = 1001, Usable = 0)
#define ViewBookmarkBitMap                        1002	//(Left Origin = 18, Top Origin = 152, Bitmap Resource ID = 1002, Usable = 0)
#define ViewBackBitMap                            1004	//(Left Origin = 25, Top Origin = 152, Bitmap Resource ID = 1004, Usable = 0)
#define ViewHomeBitMap                            1005	//(Left Origin = 34, Top Origin = 152, Bitmap Resource ID = 1005, Usable = 0)
#define ViewForwardBitMap                         1003	//(Left Origin = 43, Top Origin = 152, Bitmap Resource ID = 1003, Usable = 0)
#define ViewPlayBitMap                            1006	//(Left Origin = 125, Top Origin = 152, Bitmap Resource ID = 1006, Usable = 0)
#define ViewFindBitMap                            1008	//(Left Origin = 134, Top Origin = 152, Bitmap Resource ID = 1008, Usable = 0)
#define ViewGotoBitMap                            1009	//(Left Origin = 143, Top Origin = 152, Bitmap Resource ID = 1009, Usable = 0)
#define ViewViewGadget                            1601	//(Left Origin = 0, Top Origin = 6, Width = 160, Height = 145, Usable = 1)
#define ViewPositionGadget                        1602	//(Left Origin = 53, Top Origin = 152, Width = 70, Height = 8, Usable = 0)
#define ViewProgressGadget                        1628	//(Left Origin = 8, Top Origin = 48, Width = 142, Height = 52, Usable = 0)
#define ViewChapterGadget                         1630	//(Left Origin = 15, Top Origin = 54, Width = 128, Height = 10, Usable = 0)
#define ViewClockGadget                           1631	//(Left Origin = 126, Top Origin = 0, Width = 30, Height = 5, Usable = 1)
#define ViewBatteryGadget                         1632	//(Left Origin = 97, Top Origin = 1, Width = 20, Height = 3, Usable = 1)
#define ViewFileGadget                            1633	//(Left Origin = 15, Top Origin = 67, Width = 128, Height = 10, Usable = 0)
#define ViewCopyList                              1614	//(Left Origin = 50, Top Origin = 12, Width = 60, Usable = 0, Font = Standard, Visible Items = 3)
#define ViewMarkList                              1618	//(Left Origin = 18, Top Origin = 106, Width = 100, Usable = 0, Font = Standard, Visible Items = 4)

//	Resource: tFRM 1700
#define GotoForm                                  1700	//(Left Origin = 2, Top Origin = 40, Width = 156, Height = 118, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define GotoGo1Button                             1701	//(Left Origin = 4, Top Origin = 18, Width = 32, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define GotoFirstButton                           1705	//(Left Origin = 18, Top Origin = 37, Width = 60, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define GotoLastButton                            1706	//(Left Origin = 85, Top Origin = 37, Width = 60, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define GotoGo2Button                             1707	//(Left Origin = 4, Top Origin = 59, Width = 32, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define GotoTopButton                             1710	//(Left Origin = 18, Top Origin = 78, Width = 60, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define GotoEndButton                             1711	//(Left Origin = 85, Top Origin = 78, Width = 60, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define GotoCancelButton                          1712	//(Left Origin = 4, Top Origin = 101, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define GotoPageField                             1703	//(Left Origin = 80, Top Origin = 18, Width = 26, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 5, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 1)
#define GotoPercentField                          1709	//(Left Origin = 98, Top Origin = 60, Width = 12, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 2, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 1)
#define GotoUnnamed1702Label                      1702	//(Left Origin = 41, Top Origin = 18, Usable = 1, Font = Bold)
#define GotoUnnamed1704Label                      1704	//(Left Origin = 108, Top Origin = 18, Usable = 1, Font = Bold)
#define GotoUnnamed1708Label                      1708	//(Left Origin = 41, Top Origin = 60, Usable = 1, Font = Bold)
#define GotoTotalLabel                            1713	//(Left Origin = 121, Top Origin = 18, Usable = 1, Font = Standard)

//	Resource: tFRM 1800
#define FontForm                                  1800	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 156, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define FontOkButton                              1811	//(Left Origin = 5, Top Origin = 140, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define FontCancelButton                          1812	//(Left Origin = 48, Top Origin = 140, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define FontUseCheckbox                           1803	//(Left Origin = 5, Top Origin = 66, Width = 120, Height = 12, Usable = 1, Selected = 0, Group ID = 0, Font = Bold)
#define FontChsonlyCheckbox                       1810	//(Left Origin = 87, Top Origin = 33, Width = 64, Height = 12, Usable = 1, Selected = 1, Group ID = 0, Font = Bold)
#define FontLinespaceField                        1809	//(Left Origin = 64, Top Origin = 33, Width = 12, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 2, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 1)
#define FontWordspaceField                        1814	//(Left Origin = 94, Top Origin = 100, Width = 12, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 2, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 1)
#define FontSysfontLabel                          1801	//(Left Origin = 6, Top Origin = 18, Usable = 1, Font = Bold)
#define FontChsfontLabel                          1805	//(Left Origin = 12, Top Origin = 84, Usable = 1, Font = Bold)
#define FontSpaceLabel                            1808	//(Left Origin = 6, Top Origin = 33, Usable = 1, Font = Bold)
#define FontChsspaceLabel                         1813	//(Left Origin = 12, Top Origin = 100, Usable = 1, Font = Bold)
#define FontEngfontLabel                          1816	//(Left Origin = 6, Top Origin = 49, Usable = 1, Font = Bold)
#define FontSysfontList                           1802	//(Left Origin = 76, Top Origin = 18, Width = 70, Usable = 0, Font = Standard, Visible Items = 4)
#define FontChsfontList                           1807	//(Left Origin = 60, Top Origin = 84, Width = 70, Usable = 0, Font = Standard, Visible Items = 4)
#define FontEngfontList                           1818	//(Left Origin = 54, Top Origin = 49, Width = 70, Usable = 0, Font = Standard, Visible Items = 2)
#define FontSysfontPopTrigger                     1804	//(Left Origin = 76, Top Origin = 18, Width = 45, Height = 12, Usable = 1, Anchor Left = 1, Font = Standard, List ID = 1802)
#define FontChsfontPopTrigger                     1806	//(Left Origin = 60, Top Origin = 84, Width = 46, Height = 12, Usable = 1, Anchor Left = 1, Font = Standard, List ID = 1807)
#define FontEngfontPopTrigger                     1817	//(Left Origin = 54, Top Origin = 49, Width = 46, Height = 12, Usable = 1, Anchor Left = 1, Font = Standard, List ID = 1818)

//	Resource: tFRM 1900
#define ListoptForm                               1900	//(Left Origin = 2, Top Origin = 17, Width = 156, Height = 141, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define ListoptOkButton                           1905	//(Left Origin = 5, Top Origin = 124, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define ListoptCancelButton                       1906	//(Left Origin = 47, Top Origin = 124, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define ListoptSizeCheckbox                       1904	//(Left Origin = 6, Top Origin = 46, Width = 100, Height = 12, Usable = 1, Selected = 0, Group ID = 0, Font = Bold)
#define ListoptPdocCheckbox                       1907	//(Left Origin = 6, Top Origin = 91, Width = 100, Height = 12, Usable = 1, Selected = 0, Group ID = 0, Font = Bold)
#define ListoptPtxtCheckbox                       1909	//(Left Origin = 6, Top Origin = 106, Width = 100, Height = 12, Usable = 1, Selected = 0, Group ID = 0, Font = Bold)
#define ListoptFnameCheckbox                      1913	//(Left Origin = 6, Top Origin = 61, Width = 100, Height = 12, Usable = 1, Selected = 0, Group ID = 0, Font = Bold)
#define ListoptUnnamed1901Label                   1901	//(Left Origin = 6, Top Origin = 18, Usable = 1, Font = Bold)
#define ListoptUnnamed1908Label                   1908	//(Left Origin = 6, Top Origin = 77, Usable = 1, Font = Bold)
#define ListoptUnnamed1910Label                   1910	//(Left Origin = 20, Top Origin = 32, Usable = 1, Font = Bold)
#define ListoptSortList                           1903	//(Left Origin = 51, Top Origin = 19, Width = 40, Usable = 0, Font = Standard, Visible Items = 4)
#define ListoptFontList                           1912	//(Left Origin = 51, Top Origin = 33, Width = 60, Usable = 0, Font = Standard, Visible Items = 5)
#define ListoptSortPopTrigger                     1902	//(Left Origin = 51, Top Origin = 18, Width = 45, Height = 12, Usable = 1, Anchor Left = 1, Font = Standard, List ID = 1903)
#define ListoptFontPopTrigger                     1911	//(Left Origin = 51, Top Origin = 32, Width = 45, Height = 12, Usable = 1, Anchor Left = 1, Font = Standard, List ID = 1912)

//	Resource: tFRM 2000
#define BmkEditForm                               2000	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 156, Usable = 1, Modal = 1, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define BmkEditOpenButton                         2002	//(Left Origin = 5, Top Origin = 138, Width = 32, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define BmkEditDelButton                          2003	//(Left Origin = 44, Top Origin = 138, Width = 26, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define BmkEditCloseButton                        2004	//(Left Origin = 119, Top Origin = 138, Width = 30, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define BmkEditDelAllButton                       2005	//(Left Origin = 78, Top Origin = 138, Width = 34, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define BmkEditMarkList                           2001	//(Left Origin = 8, Top Origin = 20, Width = 140, Usable = 1, Font = Standard, Visible Items = 10)

//	Resource: tFRM 2100
#define RegisterForm                              2100	//(Left Origin = 2, Top Origin = 82, Width = 156, Height = 76, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define RegisterOKButton                          2104	//(Left Origin = 6, Top Origin = 58, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define RegisterCancelButton                      2105	//(Left Origin = 50, Top Origin = 58, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define RegisterRegField                          2103	//(Left Origin = 66, Top Origin = 36, Width = 80, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 9, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define RegisterUnnamed2107GraffitiShift          2107	//(Left Origin = 142, Top Origin = 62)
#define RegisterUnnamed2101Label                  2101	//(Left Origin = 7, Top Origin = 19, Usable = 1, Font = Bold)
#define RegisterUnnamed2102Label                  2102	//(Left Origin = 14, Top Origin = 36, Usable = 1, Font = Bold)
#define RegisterUserLabel                         2106	//(Left Origin = 66, Top Origin = 19, Usable = 1, Font = Standard)

//	Resource: tFRM 2200
#define AddBmkForm                                2200	//(Left Origin = 2, Top Origin = 101, Width = 156, Height = 57, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define AddBmkAddButton                           2202	//(Left Origin = 5, Top Origin = 40, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define AddBmkCancelButton                        2203	//(Left Origin = 47, Top Origin = 40, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define AddBmkNameField                           2201	//(Left Origin = 5, Top Origin = 20, Width = 145, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 15, Font = Standard, Auto Shift = 1, Has Scroll Bar = 0, Numeric = 0)
#define AddBmkUnnamed2204GraffitiShift            2204	//(Left Origin = 144, Top Origin = 44)

//	Resource: tFRM 2300
#define FindForm                                  2300	//(Left Origin = 2, Top Origin = 72, Width = 156, Height = 86, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define FindFindButton                            2303	//(Left Origin = 5, Top Origin = 70, Width = 30, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define FindTopButton                             2304	//(Left Origin = 42, Top Origin = 70, Width = 28, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define FindNextButton                            2305	//(Left Origin = 75, Top Origin = 70, Width = 32, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define FindCancelButton                          2306	//(Left Origin = 112, Top Origin = 70, Width = 34, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define FindCaseCheckbox                          2307	//(Left Origin = 6, Top Origin = 36, Width = 102, Height = 12, Usable = 1, Selected = 0, Group ID = 0, Font = Bold)
#define FindWholeCheckbox                         2309	//(Left Origin = 6, Top Origin = 52, Width = 144, Height = 12, Usable = 1, Selected = 0, Group ID = 0, Font = Bold)
#define FindTextField                             2302	//(Left Origin = 36, Top Origin = 18, Width = 114, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 31, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define FindUnnamed2308GraffitiShift              2308	//(Left Origin = 142, Top Origin = 36)
#define FindUnnamed2301Label                      2301	//(Left Origin = 6, Top Origin = 18, Usable = 1, Font = Bold)

//	Resource: tFRM 2400
#define RenameForm                                2400	//(Left Origin = 2, Top Origin = 87, Width = 156, Height = 71, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define RenameRenameButton                        2403	//(Left Origin = 6, Top Origin = 54, Width = 40, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define RenameCancelButton                        2404	//(Left Origin = 52, Top Origin = 54, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define RenameNameField                           2402	//(Left Origin = 5, Top Origin = 33, Width = 146, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define RenameUnnamed2405GraffitiShift            2405	//(Left Origin = 141, Top Origin = 56)
#define RenameUnnamed2401Label                    2401	//(Left Origin = 5, Top Origin = 18, Usable = 1, Font = Bold)

//	Resource: tFRM 2500
#define AutosclForm                               2500	//(Left Origin = 2, Top Origin = 57, Width = 156, Height = 101, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define AutosclOKButton                           2505	//(Left Origin = 5, Top Origin = 84, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define AutosclCancelButton                       2506	//(Left Origin = 48, Top Origin = 84, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define AutosclGuideCheckbox                      2504	//(Left Origin = 5, Top Origin = 66, Width = 120, Height = 12, Usable = 1, Selected = 1, Group ID = 0, Font = Bold)
#define AutosclUnnamed2501Label                   2501	//(Left Origin = 5, Top Origin = 18, Usable = 1, Font = Bold)
#define AutosclUnnamed2502Label                   2502	//(Left Origin = 7, Top Origin = 33, Usable = 1, Font = Standard)
#define AutosclUnnamed2503Label                   2503	//(Left Origin = 130, Top Origin = 33, Usable = 1, Font = Standard)
#define AutosclUnnamed2508Label                   2508	//(Left Origin = 5, Top Origin = 50, Usable = 1, Font = Bold)
#define AutosclMethodList                         2510	//(Left Origin = 52, Top Origin = 50, Width = 44, Usable = 0, Font = Standard, Visible Items = 2)
#define AutosclMethodPopTrigger                   2509	//(Left Origin = 52, Top Origin = 50, Width = 45, Height = 12, Usable = 1, Anchor Left = 1, Font = Standard, List ID = 2510)
#define AutosclSpeedScrollBar                     2507	//(Left Origin = 31, Top Origin = 35, Width = 92, Height = 7, Usable = 1, Value = 5, Minimum Value = 1, Maximum Value = 9, Page Size = 1)

//	Resource: tFRM 2600
#define DetailForm                                2600	//(Left Origin = 2, Top Origin = 55, Width = 156, Height = 103, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define DetailOKButton                            2607	//(Left Origin = 5, Top Origin = 86, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define DetailNameField                           2602	//(Left Origin = 40, Top Origin = 20, Width = 110, Height = 24, Usable = 1, Editable = 0, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 31, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 1)
#define DetailUnnamed2601Label                    2601	//(Left Origin = 5, Top Origin = 20, Usable = 1, Font = Bold)
#define DetailUnnamed2603Label                    2603	//(Left Origin = 8, Top Origin = 50, Usable = 1, Font = Bold)
#define DetailDateLabel                           2604	//(Left Origin = 40, Top Origin = 50, Usable = 1, Font = Standard)
#define DetailUnnamed2605Label                    2605	//(Left Origin = 13, Top Origin = 67, Usable = 1, Font = Bold)
#define DetailSizeLabel                           2606	//(Left Origin = 40, Top Origin = 67, Usable = 1, Font = Standard)

//	Resource: tFRM 2700
#define EditForm                                  2700	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 156, Usable = 1, Modal = 1, Save Behind = 0, Help ID = 0, Menu Bar ID = 1300, Default Button ID = 0)
#define EditDoneButton                            2703	//(Left Origin = 60, Top Origin = 141, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define EditTextField                             2701	//(Left Origin = 3, Top Origin = 16, Width = 142, Height = 122, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 4096, Font = Standard, Auto Shift = 0, Has Scroll Bar = 1, Numeric = 0)
#define EditVertScrollBar                         2702	//(Left Origin = 147, Top Origin = 16, Width = 7, Height = 122, Usable = 1, Value = 0, Minimum Value = 0, Maximum Value = 0, Page Size = 0)

//	Resource: tFRM 2800
#define DisplayForm                               2800	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 156, Usable = 1, Modal = 1, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define DisplayTextButton                         2804	//(Left Origin = 5, Top Origin = 55, Width = 60, Height = 12, Usable = 0, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define DisplayBackButton                         2805	//(Left Origin = 5, Top Origin = 72, Width = 60, Height = 12, Usable = 0, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define DisplayDefaultButton                      2810	//(Left Origin = 87, Top Origin = 140, Width = 42, Height = 12, Usable = 0, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define DisplayOKButton                           2816	//(Left Origin = 5, Top Origin = 140, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define DisplayCancelButton                       2817	//(Left Origin = 46, Top Origin = 140, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define DisplayStyleCheckbox                      2820	//(Left Origin = 5, Top Origin = 92, Width = 120, Height = 12, Usable = 0, Selected = 0, Group ID = 0, Font = Bold)
#define DisplaySampleGadget                       2818	//(Left Origin = 74, Top Origin = 55, Width = 77, Height = 29, Usable = 0)
#define DisplayColorLabel                         2801	//(Left Origin = 46, Top Origin = 20, Usable = 1, Font = Bold)
#define DisplayUnnamed2807Label                   2807	//(Left Origin = 5, Top Origin = 37, Usable = 0, Font = Bold)
#define DisplayUnnamed2809Label                   2809	//(Left Origin = 5, Top Origin = 112, Usable = 0, Font = Bold)
#define DisplayModesList                          2803	//(Left Origin = 80, Top Origin = 22, Width = 70, Usable = 0, Font = Standard, Visible Items = 2)
#define DisplayDayPushButton                      2806	//(Left Origin = 77, Top Origin = 112, Width = 36, Height = 12, Usable = 0, Group ID = 1, Font = Standard)
#define DisplayNightPushButton                    2808	//(Left Origin = 114, Top Origin = 112, Width = 36, Height = 12, Usable = 0, Group ID = 1, Font = Standard)
#define DisplayColorPopTrigger                    2802	//(Left Origin = 80, Top Origin = 20, Width = 30, Height = 12, Usable = 1, Anchor Left = 1, Font = Standard, List ID = 2803)
#define DisplayGroupID                            1

//	Resource: tFRM 2900
#define ButtonsForm                               2900	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 156, Usable = 1, Modal = 1, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define ButtonsOKButton                           2907	//(Left Origin = 6, Top Origin = 139, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define ButtonsCancelButton                       2908	//(Left Origin = 47, Top Origin = 139, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define ButtonsDefaultButton                      2909	//(Left Origin = 88, Top Origin = 139, Width = 40, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define ButtonsUnnamed2901Label                   2901	//(Left Origin = 6, Top Origin = 19, Usable = 1, Font = Bold)
#define ButtonsUnnamed2905Label                   2905	//(Left Origin = 6, Top Origin = 38, Usable = 1, Font = Bold)
#define ButtonsUnnamed2910Label                   2910	//(Left Origin = 80, Top Origin = 38, Usable = 1, Font = Bold)
#define ButtonsButtonsList                        2906	//(Left Origin = 6, Top Origin = 54, Width = 70, Usable = 1, Font = Standard, Visible Items = 7)
#define ButtonsActionsList                        2911	//(Left Origin = 80, Top Origin = 54, Width = 70, Usable = 1, Font = Standard, Visible Items = 7)
#define ButtonsBooksPushButton                    2902	//(Left Origin = 25, Top Origin = 18, Width = 36, Height = 12, Usable = 1, Group ID = 1, Font = Standard)
#define ButtonsTOCPushButton                      2903	//(Left Origin = 62, Top Origin = 18, Width = 36, Height = 12, Usable = 1, Group ID = 1, Font = Standard)
#define ButtonsViewPushButton                     2904	//(Left Origin = 99, Top Origin = 18, Width = 36, Height = 12, Usable = 1, Group ID = 1, Font = Standard)
#define ButtonsGroupID                            1

//	Resource: tFRM 3000
#define TapForm                                   3000	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 156, Usable = 1, Modal = 1, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define TapDefaultButton                          3006	//(Left Origin = 87, Top Origin = 139, Width = 40, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define TapOKButton                               3011	//(Left Origin = 5, Top Origin = 139, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define TapCancelButton                           3012	//(Left Origin = 46, Top Origin = 139, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define TapUnnamed3005Label                       3005	//(Left Origin = 7, Top Origin = 20, Usable = 1, Font = Bold)
#define TapUnnamed3008Label                       3008	//(Left Origin = 6, Top Origin = 120, Usable = 1, Font = Bold)
#define TapUnnamed3013Label                       3013	//(Left Origin = 94, Top Origin = 20, Usable = 1, Font = Bold)
#define TapActionsList                            3007	//(Left Origin = 94, Top Origin = 35, Width = 52, Usable = 1, Font = Standard, Visible Items = 5)
#define TapGWList                                 3010	//(Left Origin = 61, Top Origin = 121, Width = 89, Usable = 0, Font = Standard, Visible Items = 3)
#define TapQ1PushButton                           3001	//(Left Origin = 7, Top Origin = 35, Width = 78, Height = 18, Usable = 1, Group ID = 1, Font = Standard)
#define TapQ2PushButton                           3002	//(Left Origin = 7, Top Origin = 54, Width = 78, Height = 18, Usable = 1, Group ID = 1, Font = Standard)
#define TapQ3PushButton                           3003	//(Left Origin = 7, Top Origin = 73, Width = 78, Height = 18, Usable = 1, Group ID = 1, Font = Standard)
#define TapQ4PushButton                           3004	//(Left Origin = 7, Top Origin = 92, Width = 78, Height = 18, Usable = 1, Group ID = 1, Font = Standard)
#define TapGWPopTrigger                           3009	//(Left Origin = 61, Top Origin = 120, Width = 45, Height = 12, Usable = 1, Anchor Left = 1, Font = Standard, List ID = 3010)
#define TapGroupID                                1

//	Resource: tFRM 3100
#define ViewAreaForm                              3100	//(Left Origin = 2, Top Origin = 82, Width = 156, Height = 76, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define ViewAreaOKButton                          3106	//(Left Origin = 5, Top Origin = 59, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define ViewAreaCancelButton                      3107	//(Left Origin = 47, Top Origin = 59, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define ViewAreaLeftField                         3104	//(Left Origin = 54, Top Origin = 38, Width = 12, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 2, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 1)
#define ViewAreaRightField                        3105	//(Left Origin = 119, Top Origin = 38, Width = 12, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 2, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 1)
#define ViewAreaUnnamed3101Label                  3101	//(Left Origin = 11, Top Origin = 20, Usable = 1, Font = Bold)
#define ViewAreaUnnamed3102Label                  3102	//(Left Origin = 21, Top Origin = 38, Usable = 1, Font = Bold)
#define ViewAreaUnnamed3103Label                  3103	//(Left Origin = 80, Top Origin = 38, Usable = 1, Font = Bold)
#define ViewAreaUnnamed3108Label                  3108	//(Left Origin = 54, Top Origin = 20, Usable = 1, Font = Standard)

//	Resource: tFRM 3200
#define DicDAForm                                 3200	//(Left Origin = 2, Top Origin = 82, Width = 156, Height = 76, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define DicDAChooseButton                         3202	//(Left Origin = 5, Top Origin = 58, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define DicDACancelButton                         3203	//(Left Origin = 47, Top Origin = 58, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define DicDADAList                               3201	//(Left Origin = 5, Top Origin = 18, Width = 146, Usable = 1, Font = Standard, Visible Items = 3)

//	Resource: tFRM 3300
#define VDictForm                                 3300	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 156, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 1400, Default Button ID = 0)
#define VDictOKButton                             3302	//(Left Origin = 5, Top Origin = 139, Width = 36, Height = 12, Usable = 0, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define VDictCancelButton                         3303	//(Left Origin = 47, Top Origin = 139, Width = 36, Height = 12, Usable = 0, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define VDictPrevButton                           3305	//(Left Origin = 7, Top Origin = 22, Width = 14, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define VDictNextButton                           3306	//(Left Origin = 26, Top Origin = 22, Width = 14, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define VDictNewButton                            3307	//(Left Origin = 76, Top Origin = 22, Width = 22, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define VDictCloseButton                          3309	//(Left Origin = 135, Top Origin = 22, Width = 14, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define VDictCaseButton                           3310	//(Left Origin = 45, Top Origin = 22, Width = 26, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define VDictWordField                            3304	//(Left Origin = 4, Top Origin = 5, Width = 148, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 65, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define VDictMeanGadget                           3308	//(Left Origin = 5, Top Origin = 40, Width = 146, Height = 112, Usable = 1)
#define VDictDictsList                            3301	//(Left Origin = 6, Top Origin = 16, Width = 144, Usable = 0, Font = Standard, Visible Items = 10)

//	Resource: tFRM 3400
#define ExportForm                                3400	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 156, Usable = 1, Modal = 1, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define ExportConvertButton                       3411	//(Left Origin = 5, Top Origin = 139, Width = 44, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define ExportCancelButton                        3413	//(Left Origin = 56, Top Origin = 139, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define ExportTitleField                          3402	//(Left Origin = 40, Top Origin = 20, Width = 100, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 32, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define ExportDirField                            3408	//(Left Origin = 57, Top Origin = 89, Width = 90, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define ExportProgressGadget                      3410	//(Left Origin = 57, Top Origin = 109, Width = 90, Height = 13, Usable = 1)
#define ExportUnnamed3401Label                    3401	//(Left Origin = 6, Top Origin = 20, Usable = 1, Font = Bold)
#define ExportUnnamed3403Label                    3403	//(Left Origin = 11, Top Origin = 39, Usable = 1, Font = Bold)
#define ExportSizeLabel                           3404	//(Left Origin = 40, Top Origin = 39, Usable = 1, Font = Standard)
#define ExportUnnamed3405Label                    3405	//(Left Origin = 9, Top Origin = 58, Usable = 1, Font = Bold)
#define ExportUnnamed3407Label                    3407	//(Left Origin = 36, Top Origin = 90, Usable = 1, Font = Bold)
#define ExportUnnamed3409Label                    3409	//(Left Origin = 6, Top Origin = 110, Usable = 1, Font = Bold)
#define ExportPosList                             3406	//(Left Origin = 58, Top Origin = 58, Width = 80, Usable = 1, Font = Standard, Visible Items = 2)


//	Resource: Talt 1001
#define RomIncompatibleAlert                      1001
#define RomIncompatibleOK                         0

//	Resource: Talt 1002
#define ExpansionAlert                            1002
#define ExpansionOK                               0

//	Resource: Talt 1003
#define MissZLibAlert                             1003
#define MissZLibOK                                0

//	Resource: Talt 1004
#define CannotAddAlert                            1004
#define CannotAddOK                               0

//	Resource: Talt 1005
#define InvalidSelAlert                           1005
#define InvalidSelOK                              0

//	Resource: Talt 1006
#define DelBookAlert                              1006
#define DelBookDelete                             0
#define DelBookCancel                             1

//	Resource: Talt 1007
#define InvalidDocAlert                           1007
#define InvalidDocOK                              0

//	Resource: Talt 1008
#define RegisteredAlert                           1008
#define RegisteredOK                              0

//	Resource: Talt 1009
#define RegErrorAlert                             1009
#define RegErrorOK                                0

//	Resource: Talt 1010
#define RegSucceedAlert                           1010
#define RegSucceedOK                              0

//	Resource: Talt 1011
#define DelAllBmkAlert                            1011
#define DelAllBmkYes                              0
#define DelAllBmkNo                               1

//	Resource: Talt 1012
#define NofoundAlert                              1012
#define NofoundOK                                 0

//	Resource: Talt 1013
#define CateSelAlert                              1013
#define CateSelOK                                 0

//	Resource: Talt 1017
#define SyncAlert                                 1017
#define SyncSynchronize                           0
#define SyncCancel                                1

//	Resource: Talt 1018
#define NeedRegAlert                              1018
#define NeedRegOK                                 0

//	Resource: Talt 1100
#define WelcomeAlert                              1100
#define WelcomeIsee                               0

//	Resource: Talt 1200
#define ExpireAlert                               1200
#define ExpireOK                                  0

//	Resource: Talt 1000
#define DebugAlert                                1000
#define DebugOK                                   0

//	Resource: Talt 1300
#define MissDicAlert                              1300
#define MissDicOK                                 0

//	Resource: Talt 1400
#define OpErrAlert                                1400
#define OpErrOK                                   0


//	Resource: MBAR 1000
#define MainFormMenuBar                           1000

//	Resource: MBAR 1100
#define ViewFormMenuBar                           1100

//	Resource: MBAR 1200
#define ContFormMenuBar                           1200

//	Resource: MBAR 1300
#define EditFormMenuBar                           1300

//	Resource: MBAR 1400
#define VDictFormMenuBar                          1400


//	Resource: MENU 1000
#define F1OptionsMenu                             1000
#define F1OptionsDisplay                          1000
#define F1OptionsBookList                         1001
#define F1OptionsFont                             1002
#define F1OptionsButtons                          1003
#define F1OptionsRegister                         1005
#define F1OptionsAboutVBook                       1006

//	Resource: MENU 1100
#define F1BookMenu                                1100
#define F1BookInHandheld                          1100	//  Command Key: H
#define F1BookInCard                              1101	//  Command Key: C
#define F1BookScanBook                            1103	//  Command Key: S
#define F1BookSaveList                            1104	//  Command Key: L
#define F1BookSelectAll                           1106
#define F1BookUnselectAll                         1107
#define F1BookDelete                              1109
#define F1BookSyncBookInfo                        1111

//	Resource: MENU 1200
#define F1ToolsMenu                               1200
#define F1ToolsSortbyTitle                        1200	//  Command Key: 1
#define F1ToolsSortbyDate                         1201	//  Command Key: 2
#define F1ToolsSortbySize                         1202	//  Command Key: 3
#define F1ToolsRuntimeInformation                 1204

//	Resource: MENU 1300
#define F3BookMenu                                1300
#define F3BookTOC                                 1300	//  Command Key: C
#define F3BookAddBookmark                         1302	//  Command Key: A
#define F3BookEditBookmarks                       1303	//  Command Key: B
#define F3BookExternalDA                          1305
#define F3BookClose                               1307	//  Command Key: E
#define F3BookDayNight                            1309	//  Command Key: 7

//	Resource: MENU 1400
#define F3ViewMenu                                1400
#define F3ViewHome                                1400	//  Command Key: H
#define F3ViewBack                                1401	//  Command Key: 1
#define F3ViewForward                             1402	//  Command Key: 2
#define F3ViewGotoTop                             1404	//  Command Key: 0
#define F3ViewGotoBottom                          1405	//  Command Key: Z
#define F3ViewGoto                                1406	//  Command Key: O
#define F3ViewAutoScroll                          1408	//  Command Key: S
#define F3ViewInvert                              1410	//  Command Key: I
#define F3ViewBatteryClock                        1411	//  Command Key: Y
#define F3ViewToolbar                             1412	//  Command Key: T

//	Resource: MENU 1500
#define F3OptionsMenu                             1500
#define F3OptionsDisplay                          1500
#define F3OptionsFont                             1501
#define F3OptionsScroll                           1502
#define F3OptionsButtons                          1503
#define F3OptionsTap                              1504
#define F3OptionsView                             1505
#define F3OptionsAboutVBook                       1507

//	Resource: MENU 1600
#define F3EditMenu                                1600
#define F3EditFind                                1600	//  Command Key: F
#define F3EditFindNext                            1601	//  Command Key: N
#define F3EditScreenCopy                          1603	//  Command Key: P
#define F3EditCopyMode                            1604	//  Command Key: 5
#define F3EditGetWord                             1606	//  Command Key: G
#define F3EditParagraphIndent                     1608

//	Resource: MENU 1700
#define F2TOCMenu                                 1700
#define F2TOCBack                                 1700	//  Command Key: B

//	Resource: MENU 1800
#define F4EditMenu                                1800
#define F4EditUndo                                1800	//  Command Key: U
#define F4EditCut                                 1801	//  Command Key: X
#define F4EditCopy                                1802	//  Command Key: C
#define F4EditPaste                               1803	//  Command Key: P
#define F4EditSelectAll                           1804	//  Command Key: S

//	Resource: MENU 1900
#define F2OptionsMenu                             1900
#define F2OptionsButtons                          1900

//	Resource: MENU 2000
#define F5DictMenu                                2000
#define F5DictChoose                              2000
#define F5DictRefresh                             2001
#define F5DictCaseSwitch                          2003


//	Resource: tSTR 1200
#define SyncBookString                            1200	// "Synchronizing..."

//	Resource: tSTR 1000
#define AboutString                               1000	// "VBook is a reader with special support for chinese.  VBook is shareware, if you feel this software is useful, please purchase it via http://pda.softreg.com.cn.  SysZLib.prc Copyright © 1995-1998 Jean-loup Gailly."

//	Resource: tSTR 1100
#define ScanBookString                            1100	// "Scaning book..."

//	Resource: tSTR 1300
#define SearchString                              1300	// "Searching..."

//	Resource: tSTR 1400
#define SaveListString                            1400	// "Saving book list..."

//	Resource: tSTR 1500
#define LoadingString                             1500	// "Loading..."

//	Resource: tSTR 1600
#define DeletingString                            1600	// "Deleting..."


//	Resource: tSTL 1100
#define BookmarkStringList                        1100

//	Resource: tSTL 1300
#define BooksActionsStringList                    1300

//	Resource: tSTL 1200
#define ModesStringList                           1200

//	Resource: tSTL 1000
#define CategoryStringList                        1000

//	Resource: tSTL 1400
#define TOCActionsStringList                      1400

//	Resource: tSTL 1500
#define ViewActionsStringList                     1500

//	Resource: tSTL 1600
#define MemOpStringList                           1600

//	Resource: tSTL 1700
#define VfsOpStringList                           1700


//	Resource: PICT 1001
#define Largeicon2Bitmap                          1001

//	Resource: PICT 1000
#define Largeicon1Bitmap                          1000

//	Resource: PICT 1008
#define Laregicon8HRBitmap                        1008

//	Resource: PICT 1011
#define Smallicon2Bitmap                          1011

//	Resource: PICT 1003
#define Largeicon8Bitmap                          1003

//	Resource: PICT 1018
#define Smallicon8HRBitmap                        1018

//	Resource: PICT 1020
#define Close1Bitmap                              1020

//	Resource: PICT 1023
#define Close8Bitmap                              1023

//	Resource: PICT 1030
#define TOC1Bitmap                                1030

//	Resource: PICT 1033
#define TOC8Bitmap                                1033

//	Resource: PICT 1040
#define BM1Bitmap                                 1040

//	Resource: PICT 1043
#define BM8Bitmap                                 1043

//	Resource: PICT 1050
#define Back1Bitmap                               1050

//	Resource: PICT 1053
#define Back8Bitmap                               1053

//	Resource: PICT 1060
#define Forward1Bitmap                            1060

//	Resource: PICT 1063
#define Forward8Bitmap                            1063

//	Resource: PICT 1070
#define Home1Bitmap                               1070

//	Resource: PICT 1010
#define Smallicon1Bitmap                          1010

//	Resource: PICT 1013
#define Smallicon8Bitmap                          1013

//	Resource: PICT 1073
#define Home8Bitmap                               1073

//	Resource: PICT 1080
#define Play1Bitmap                               1080

//	Resource: PICT 1083
#define Play8Bitmap                               1083

//	Resource: PICT 1090
#define Stop1Bitmap                               1090

//	Resource: PICT 1093
#define Stop8Bitmap                               1093

//	Resource: PICT 1100
#define Find1Bitmap                               1100

//	Resource: PICT 1103
#define Find8Bitmap                               1103

//	Resource: PICT 1110
#define Goto1Bitmap                               1110

//	Resource: PICT 1113
#define Goto8Bitmap                               1113

//	Resource: PICT 1120
#define Capture1Bitmap                            1120

//	Resource: PICT 1123
#define Capture8Bitmap                            1123

//	Resource: PICT 1170
#define Up1Bitmap                                 1170

//	Resource: PICT 1173
#define Up8Bitmap                                 1173

//	Resource: PICT 1180
#define Return1Bitmap                             1180

//	Resource: PICT 1190
#define Battery1Bitmap                            1190

//	Resource: PICT 1183
#define Return8Bitmap                             1183

//	Resource: PICT 1193
#define Battery8Bitmap                            1193

//	Resource: PICT 1028
#define Close8HRBitmap                            1028

//	Resource: PICT 1038
#define TOC8HRBitmap                              1038

//	Resource: PICT 1048
#define BM8HRBitmap                               1048

//	Resource: PICT 1198
#define Battery8HRBitmap                          1198

//	Resource: PICT 1068
#define Forward8HRBitmap                          1068

//	Resource: PICT 1058
#define Back8HRBitmap                             1058

//	Resource: PICT 1078
#define Home8HRBitmap                             1078

//	Resource: PICT 1088
#define Play8HRBitmap                             1088

//	Resource: PICT 1098
#define Stop8HRBitmap                             1098

//	Resource: PICT 1108
#define Find8HRBitmap                             1108

//	Resource: PICT 1118
#define Goto8HRBitmap                             1118

//	Resource: PICT 1128
#define Capture8HRBitmap                          1128

//	Resource: PICT 1178
#define Up8HRBitmap                               1178

//	Resource: PICT 1188
#define Return8HRBitmap                           1188

//	Resource: PICT 1200
#define Handheld1Bitmap                           1200

//	Resource: PICT 1203
#define Handheld8Bitmap                           1203

//	Resource: PICT 1208
#define Handheld8HRBitmap                         1208

//	Resource: PICT 1210
#define Card1Bitmap                               1210

//	Resource: PICT 1213
#define Card8Bitmap                               1213

//	Resource: PICT 1218
#define Card8HRBitmap                             1218

//	Resource: PICT 1220
#define Copy1Bitmap                               1220

//	Resource: PICT 1223
#define Copy8Bitmap                               1223

//	Resource: PICT 1228
#define Copy8HRBitmap                             1228

//	Resource: PICT 1230
#define CopyPressed1Bitmap                        1230

//	Resource: PICT 1233
#define CopyPressed8Bitmap                        1233

//	Resource: PICT 1238
#define CopyPressed8HRBitmap                      1238


//	Resource: tbmf 1000
#define CloseBitmapFamily                         1000

//	Resource: tbmf 1001
#define TOCBitmapFamily                           1001

//	Resource: tbmf 1002
#define BMBitmapFamily                            1002

//	Resource: tbmf 1003
#define ForwardBitmapFamily                       1003

//	Resource: tbmf 1004
#define BackBitmapFamily                          1004

//	Resource: tbmf 1005
#define HomeBitmapFamily                          1005

//	Resource: tbmf 1006
#define PlayBitmapFamily                          1006

//	Resource: tbmf 1007
#define StopBitmapFamily                          1007

//	Resource: tbmf 1008
#define FindBitmapFamily                          1008

//	Resource: tbmf 1009
#define GotoBitmapFamily                          1009

//	Resource: tbmf 1010
#define CaptureBitmapFamily                       1010

//	Resource: tbmf 1011
#define UpBitmapFamily                            1011

//	Resource: tbmf 1012
#define ReturnBitmapFamily                        1012

//	Resource: tbmf 1013
#define BatteryBitmapFamily                       1013

//	Resource: tbmf 1100
#define VBookBitmapFamily                         1100

//	Resource: tbmf 1014
#define HandheldBitmapFamily                      1014

//	Resource: tbmf 1015
#define CardBitmapFamily                          1015

//	Resource: tbmf 1200
#define CopyBitmapFamily                          1200

//	Resource: tbmf 1300
#define CopyPressedBitmapFamily                   1300


//	Resource: taif 1000
#define Largeicons12and8bitsAppIconFamily         1000

//	Resource: taif 1001
#define Smallicons12and8bitsAppIconFamily         1001


#endif // VBOOKRSC_H
